from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass
from pathlib import Path


FUNCTION_FILENAME = "ask.fish"
MANAGED_MARKER = "# ask-ai-managed: true"


class InstallError(RuntimeError):
    pass


@dataclass(frozen=True)
class InstallResult:
    path: Path
    project_dir: Path
    changed: bool
    replaced: bool


@dataclass(frozen=True)
class UninstallResult:
    path: Path
    removed: bool


def install_fish_function(force: bool = False) -> InstallResult:
    path = fish_function_path()
    project_dir = discover_project_dir()
    content = fish_function_content(project_dir)

    current = None
    if path.exists():
        current = path.read_text(encoding="utf-8")
        if MANAGED_MARKER not in current and not force:
            raise InstallError(
                f"{path} already exists and is not managed by ask-ai. "
                "Use `ask install --force` to replace it."
            )

    if current == content:
        return InstallResult(
            path=path,
            project_dir=project_dir,
            changed=False,
            replaced=False,
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return InstallResult(
        path=path,
        project_dir=project_dir,
        changed=True,
        replaced=current is not None,
    )


def uninstall_fish_function(force: bool = False) -> UninstallResult:
    path = fish_function_path()
    if not path.exists():
        return UninstallResult(path=path, removed=False)

    current = path.read_text(encoding="utf-8")
    if MANAGED_MARKER not in current and not force:
        raise InstallError(
            f"{path} is not managed by ask-ai. "
            "Use `ask uninstall --force` to remove it anyway."
        )

    path.unlink()
    return UninstallResult(path=path, removed=True)


def fish_function_path() -> Path:
    return fish_functions_dir() / FUNCTION_FILENAME


def fish_functions_dir() -> Path:
    config_home = os.environ.get("XDG_CONFIG_HOME")
    if config_home:
        return Path(config_home).expanduser() / "fish" / "functions"
    return Path.home() / ".config" / "fish" / "functions"


def fish_function_content(project_dir: Path) -> str:
    project = _fish_quote(str(project_dir))
    return "\n".join(
        [
            "# Generated by ask-ai.",
            MANAGED_MARKER,
            "function ask --description 'Ask DeepSeek with ask-ai'",
            f"    command uv run --project {project} ask $argv",
            "end",
            "",
        ]
    )


def discover_project_dir() -> Path:
    starts = [Path.cwd(), Path(__file__).resolve()]
    for start in starts:
        root = _find_project_root(start)
        if root is not None:
            return root
    raise InstallError(
        "could not find the ask-ai project root. "
        "Run `uv run ask install` from the source checkout."
    )


def _find_project_root(start: Path) -> Path | None:
    base = start if start.is_dir() else start.parent
    for path in [base, *base.parents]:
        pyproject = path / "pyproject.toml"
        if _is_ask_ai_project(pyproject):
            return path
    return None


def _is_ask_ai_project(path: Path) -> bool:
    try:
        with path.open("rb") as file:
            data = tomllib.load(file)
    except (OSError, tomllib.TOMLDecodeError):
        return False
    return data.get("project", {}).get("name") == "ask-ai"


def _fish_quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"
